# -*- coding: utf-8 -*-
"""main.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QBcy28AOp8eQsm_1vUS5NURo2FHWiq-7
"""

from google.colab import drive
from torch.utils.data import DataLoader
from models.anomaly_model import HyperbolicVideoAnomalyModel
from data.dataset import VideoFeatureDataset
from utils.training import train_with_validation

drive.mount('/content/drive')

train_ds = VideoFeatureDataset("/content/drive/MyDrive/aaa/entrenamiento", "/content/drive/MyDrive/aaa/train_labels.json")
val_ds = VideoFeatureDataset("/content/drive/MyDrive/aaa/validacion", "/content/drive/MyDrive/aaa/val_labels.json")
test_ds = VideoFeatureDataset("/content/drive/MyDrive/aaa/prueba", "/content/drive/MyDrive/aaa/test_labels.json")

train_loader = DataLoader(train_ds, batch_size=4, shuffle=True)
val_loader = DataLoader(val_ds, batch_size=4)
test_loader = DataLoader(test_ds, batch_size=4)

model = HyperbolicVideoAnomalyModel()
train_with_validation(model, train_loader, val_loader, save_path="/content/drive/MyDrive/aaa/best_model.pt",
                      log_path="/content/drive/MyDrive/aaa/train_log.csv", epochs=100)

print(f"Entrenamiento: {len(train_ds)} muestras")
print(f"Validación: {len(val_ds)} muestras")
print(f"Prueba: {len(test_ds)} muestras")